# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yanxx/CLionProjects/redis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yanxx/CLionProjects/redis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yanxx/CLionProjects/redis/CMakeFiles /Users/yanxx/CLionProjects/redis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yanxx/CLionProjects/redis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redis-cli

# Build rule for target.
redis-cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redis-cli
.PHONY : redis-cli

# fast build rule for target.
redis-cli/fast:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/build
.PHONY : redis-cli/fast

#=============================================================================
# Target rules for targets named redis-server

# Build rule for target.
redis-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redis-server
.PHONY : redis-server

# fast build rule for target.
redis-server/fast:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/build
.PHONY : redis-server/fast

#=============================================================================
# Target rules for targets named hiredis

# Build rule for target.
hiredis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hiredis
.PHONY : hiredis

# fast build rule for target.
hiredis/fast:
	$(MAKE) -f deps/hiredis/CMakeFiles/hiredis.dir/build.make deps/hiredis/CMakeFiles/hiredis.dir/build
.PHONY : hiredis/fast

#=============================================================================
# Target rules for targets named linenoise

# Build rule for target.
linenoise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linenoise
.PHONY : linenoise

# fast build rule for target.
linenoise/fast:
	$(MAKE) -f deps/linenoise/CMakeFiles/linenoise.dir/build.make deps/linenoise/CMakeFiles/linenoise.dir/build
.PHONY : linenoise/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) -f deps/lua/CMakeFiles/lua.dir/build.make deps/lua/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named testmodule

# Build rule for target.
testmodule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testmodule
.PHONY : testmodule

# fast build rule for target.
testmodule/fast:
	$(MAKE) -f src/modules/CMakeFiles/testmodule.dir/build.make src/modules/CMakeFiles/testmodule.dir/build
.PHONY : testmodule/fast

#=============================================================================
# Target rules for targets named helloblock

# Build rule for target.
helloblock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloblock
.PHONY : helloblock

# fast build rule for target.
helloblock/fast:
	$(MAKE) -f src/modules/CMakeFiles/helloblock.dir/build.make src/modules/CMakeFiles/helloblock.dir/build
.PHONY : helloblock/fast

#=============================================================================
# Target rules for targets named hellotype

# Build rule for target.
hellotype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hellotype
.PHONY : hellotype

# fast build rule for target.
hellotype/fast:
	$(MAKE) -f src/modules/CMakeFiles/hellotype.dir/build.make src/modules/CMakeFiles/hellotype.dir/build
.PHONY : hellotype/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) -f src/modules/CMakeFiles/helloworld.dir/build.make src/modules/CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

src/acl.o: src/acl.c.o

.PHONY : src/acl.o

# target to build an object file
src/acl.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/acl.c.o
.PHONY : src/acl.c.o

src/acl.i: src/acl.c.i

.PHONY : src/acl.i

# target to preprocess a source file
src/acl.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/acl.c.i
.PHONY : src/acl.c.i

src/acl.s: src/acl.c.s

.PHONY : src/acl.s

# target to generate assembly for a file
src/acl.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/acl.c.s
.PHONY : src/acl.c.s

src/adlist.o: src/adlist.c.o

.PHONY : src/adlist.o

# target to build an object file
src/adlist.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/adlist.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/adlist.c.o
.PHONY : src/adlist.c.o

src/adlist.i: src/adlist.c.i

.PHONY : src/adlist.i

# target to preprocess a source file
src/adlist.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/adlist.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/adlist.c.i
.PHONY : src/adlist.c.i

src/adlist.s: src/adlist.c.s

.PHONY : src/adlist.s

# target to generate assembly for a file
src/adlist.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/adlist.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/adlist.c.s
.PHONY : src/adlist.c.s

src/ae.o: src/ae.c.o

.PHONY : src/ae.o

# target to build an object file
src/ae.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/ae.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ae.c.o
.PHONY : src/ae.c.o

src/ae.i: src/ae.c.i

.PHONY : src/ae.i

# target to preprocess a source file
src/ae.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/ae.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ae.c.i
.PHONY : src/ae.c.i

src/ae.s: src/ae.c.s

.PHONY : src/ae.s

# target to generate assembly for a file
src/ae.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/ae.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ae.c.s
.PHONY : src/ae.c.s

src/ae_kqueue.o: src/ae_kqueue.c.o

.PHONY : src/ae_kqueue.o

# target to build an object file
src/ae_kqueue.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ae_kqueue.c.o
.PHONY : src/ae_kqueue.c.o

src/ae_kqueue.i: src/ae_kqueue.c.i

.PHONY : src/ae_kqueue.i

# target to preprocess a source file
src/ae_kqueue.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ae_kqueue.c.i
.PHONY : src/ae_kqueue.c.i

src/ae_kqueue.s: src/ae_kqueue.c.s

.PHONY : src/ae_kqueue.s

# target to generate assembly for a file
src/ae_kqueue.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ae_kqueue.c.s
.PHONY : src/ae_kqueue.c.s

src/anet.o: src/anet.c.o

.PHONY : src/anet.o

# target to build an object file
src/anet.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/anet.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/anet.c.o
.PHONY : src/anet.c.o

src/anet.i: src/anet.c.i

.PHONY : src/anet.i

# target to preprocess a source file
src/anet.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/anet.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/anet.c.i
.PHONY : src/anet.c.i

src/anet.s: src/anet.c.s

.PHONY : src/anet.s

# target to generate assembly for a file
src/anet.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/anet.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/anet.c.s
.PHONY : src/anet.c.s

src/aof.o: src/aof.c.o

.PHONY : src/aof.o

# target to build an object file
src/aof.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/aof.c.o
.PHONY : src/aof.c.o

src/aof.i: src/aof.c.i

.PHONY : src/aof.i

# target to preprocess a source file
src/aof.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/aof.c.i
.PHONY : src/aof.c.i

src/aof.s: src/aof.c.s

.PHONY : src/aof.s

# target to generate assembly for a file
src/aof.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/aof.c.s
.PHONY : src/aof.c.s

src/bio.o: src/bio.c.o

.PHONY : src/bio.o

# target to build an object file
src/bio.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/bio.c.o
.PHONY : src/bio.c.o

src/bio.i: src/bio.c.i

.PHONY : src/bio.i

# target to preprocess a source file
src/bio.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/bio.c.i
.PHONY : src/bio.c.i

src/bio.s: src/bio.c.s

.PHONY : src/bio.s

# target to generate assembly for a file
src/bio.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/bio.c.s
.PHONY : src/bio.c.s

src/bitops.o: src/bitops.c.o

.PHONY : src/bitops.o

# target to build an object file
src/bitops.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/bitops.c.o
.PHONY : src/bitops.c.o

src/bitops.i: src/bitops.c.i

.PHONY : src/bitops.i

# target to preprocess a source file
src/bitops.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/bitops.c.i
.PHONY : src/bitops.c.i

src/bitops.s: src/bitops.c.s

.PHONY : src/bitops.s

# target to generate assembly for a file
src/bitops.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/bitops.c.s
.PHONY : src/bitops.c.s

src/blocked.o: src/blocked.c.o

.PHONY : src/blocked.o

# target to build an object file
src/blocked.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/blocked.c.o
.PHONY : src/blocked.c.o

src/blocked.i: src/blocked.c.i

.PHONY : src/blocked.i

# target to preprocess a source file
src/blocked.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/blocked.c.i
.PHONY : src/blocked.c.i

src/blocked.s: src/blocked.c.s

.PHONY : src/blocked.s

# target to generate assembly for a file
src/blocked.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/blocked.c.s
.PHONY : src/blocked.c.s

src/childinfo.o: src/childinfo.c.o

.PHONY : src/childinfo.o

# target to build an object file
src/childinfo.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/childinfo.c.o
.PHONY : src/childinfo.c.o

src/childinfo.i: src/childinfo.c.i

.PHONY : src/childinfo.i

# target to preprocess a source file
src/childinfo.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/childinfo.c.i
.PHONY : src/childinfo.c.i

src/childinfo.s: src/childinfo.c.s

.PHONY : src/childinfo.s

# target to generate assembly for a file
src/childinfo.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/childinfo.c.s
.PHONY : src/childinfo.c.s

src/cluster.o: src/cluster.c.o

.PHONY : src/cluster.o

# target to build an object file
src/cluster.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/cluster.c.o
.PHONY : src/cluster.c.o

src/cluster.i: src/cluster.c.i

.PHONY : src/cluster.i

# target to preprocess a source file
src/cluster.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/cluster.c.i
.PHONY : src/cluster.c.i

src/cluster.s: src/cluster.c.s

.PHONY : src/cluster.s

# target to generate assembly for a file
src/cluster.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/cluster.c.s
.PHONY : src/cluster.c.s

src/config.o: src/config.c.o

.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/config.c.s
.PHONY : src/config.c.s

src/crc16.o: src/crc16.c.o

.PHONY : src/crc16.o

# target to build an object file
src/crc16.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc16.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/crc16.c.o
.PHONY : src/crc16.c.o

src/crc16.i: src/crc16.c.i

.PHONY : src/crc16.i

# target to preprocess a source file
src/crc16.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc16.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/crc16.c.i
.PHONY : src/crc16.c.i

src/crc16.s: src/crc16.c.s

.PHONY : src/crc16.s

# target to generate assembly for a file
src/crc16.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc16.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/crc16.c.s
.PHONY : src/crc16.c.s

src/crc64.o: src/crc64.c.o

.PHONY : src/crc64.o

# target to build an object file
src/crc64.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc64.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/crc64.c.o
.PHONY : src/crc64.c.o

src/crc64.i: src/crc64.c.i

.PHONY : src/crc64.i

# target to preprocess a source file
src/crc64.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc64.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/crc64.c.i
.PHONY : src/crc64.c.i

src/crc64.s: src/crc64.c.s

.PHONY : src/crc64.s

# target to generate assembly for a file
src/crc64.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc64.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/crc64.c.s
.PHONY : src/crc64.c.s

src/db.o: src/db.c.o

.PHONY : src/db.o

# target to build an object file
src/db.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/db.c.o
.PHONY : src/db.c.o

src/db.i: src/db.c.i

.PHONY : src/db.i

# target to preprocess a source file
src/db.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/db.c.i
.PHONY : src/db.c.i

src/db.s: src/db.c.s

.PHONY : src/db.s

# target to generate assembly for a file
src/db.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/db.c.s
.PHONY : src/db.c.s

src/debug.o: src/debug.c.o

.PHONY : src/debug.o

# target to build an object file
src/debug.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/debug.c.o
.PHONY : src/debug.c.o

src/debug.i: src/debug.c.i

.PHONY : src/debug.i

# target to preprocess a source file
src/debug.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/debug.c.i
.PHONY : src/debug.c.i

src/debug.s: src/debug.c.s

.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/debug.c.s
.PHONY : src/debug.c.s

src/defrag.o: src/defrag.c.o

.PHONY : src/defrag.o

# target to build an object file
src/defrag.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/defrag.c.o
.PHONY : src/defrag.c.o

src/defrag.i: src/defrag.c.i

.PHONY : src/defrag.i

# target to preprocess a source file
src/defrag.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/defrag.c.i
.PHONY : src/defrag.c.i

src/defrag.s: src/defrag.c.s

.PHONY : src/defrag.s

# target to generate assembly for a file
src/defrag.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/defrag.c.s
.PHONY : src/defrag.c.s

src/dict.o: src/dict.c.o

.PHONY : src/dict.o

# target to build an object file
src/dict.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/dict.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/dict.c.o
.PHONY : src/dict.c.o

src/dict.i: src/dict.c.i

.PHONY : src/dict.i

# target to preprocess a source file
src/dict.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/dict.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/dict.c.i
.PHONY : src/dict.c.i

src/dict.s: src/dict.c.s

.PHONY : src/dict.s

# target to generate assembly for a file
src/dict.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/dict.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/dict.c.s
.PHONY : src/dict.c.s

src/endianconv.o: src/endianconv.c.o

.PHONY : src/endianconv.o

# target to build an object file
src/endianconv.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/endianconv.c.o
.PHONY : src/endianconv.c.o

src/endianconv.i: src/endianconv.c.i

.PHONY : src/endianconv.i

# target to preprocess a source file
src/endianconv.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/endianconv.c.i
.PHONY : src/endianconv.c.i

src/endianconv.s: src/endianconv.c.s

.PHONY : src/endianconv.s

# target to generate assembly for a file
src/endianconv.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/endianconv.c.s
.PHONY : src/endianconv.c.s

src/evict.o: src/evict.c.o

.PHONY : src/evict.o

# target to build an object file
src/evict.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/evict.c.o
.PHONY : src/evict.c.o

src/evict.i: src/evict.c.i

.PHONY : src/evict.i

# target to preprocess a source file
src/evict.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/evict.c.i
.PHONY : src/evict.c.i

src/evict.s: src/evict.c.s

.PHONY : src/evict.s

# target to generate assembly for a file
src/evict.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/evict.c.s
.PHONY : src/evict.c.s

src/expire.o: src/expire.c.o

.PHONY : src/expire.o

# target to build an object file
src/expire.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/expire.c.o
.PHONY : src/expire.c.o

src/expire.i: src/expire.c.i

.PHONY : src/expire.i

# target to preprocess a source file
src/expire.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/expire.c.i
.PHONY : src/expire.c.i

src/expire.s: src/expire.c.s

.PHONY : src/expire.s

# target to generate assembly for a file
src/expire.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/expire.c.s
.PHONY : src/expire.c.s

src/geo.o: src/geo.c.o

.PHONY : src/geo.o

# target to build an object file
src/geo.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geo.c.o
.PHONY : src/geo.c.o

src/geo.i: src/geo.c.i

.PHONY : src/geo.i

# target to preprocess a source file
src/geo.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geo.c.i
.PHONY : src/geo.c.i

src/geo.s: src/geo.c.s

.PHONY : src/geo.s

# target to generate assembly for a file
src/geo.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geo.c.s
.PHONY : src/geo.c.s

src/geohash.o: src/geohash.c.o

.PHONY : src/geohash.o

# target to build an object file
src/geohash.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geohash.c.o
.PHONY : src/geohash.c.o

src/geohash.i: src/geohash.c.i

.PHONY : src/geohash.i

# target to preprocess a source file
src/geohash.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geohash.c.i
.PHONY : src/geohash.c.i

src/geohash.s: src/geohash.c.s

.PHONY : src/geohash.s

# target to generate assembly for a file
src/geohash.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geohash.c.s
.PHONY : src/geohash.c.s

src/geohash_helper.o: src/geohash_helper.c.o

.PHONY : src/geohash_helper.o

# target to build an object file
src/geohash_helper.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geohash_helper.c.o
.PHONY : src/geohash_helper.c.o

src/geohash_helper.i: src/geohash_helper.c.i

.PHONY : src/geohash_helper.i

# target to preprocess a source file
src/geohash_helper.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geohash_helper.c.i
.PHONY : src/geohash_helper.c.i

src/geohash_helper.s: src/geohash_helper.c.s

.PHONY : src/geohash_helper.s

# target to generate assembly for a file
src/geohash_helper.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/geohash_helper.c.s
.PHONY : src/geohash_helper.c.s

src/gopher.o: src/gopher.c.o

.PHONY : src/gopher.o

# target to build an object file
src/gopher.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/gopher.c.o
.PHONY : src/gopher.c.o

src/gopher.i: src/gopher.c.i

.PHONY : src/gopher.i

# target to preprocess a source file
src/gopher.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/gopher.c.i
.PHONY : src/gopher.c.i

src/gopher.s: src/gopher.c.s

.PHONY : src/gopher.s

# target to generate assembly for a file
src/gopher.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/gopher.c.s
.PHONY : src/gopher.c.s

src/hyperloglog.o: src/hyperloglog.c.o

.PHONY : src/hyperloglog.o

# target to build an object file
src/hyperloglog.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/hyperloglog.c.o
.PHONY : src/hyperloglog.c.o

src/hyperloglog.i: src/hyperloglog.c.i

.PHONY : src/hyperloglog.i

# target to preprocess a source file
src/hyperloglog.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/hyperloglog.c.i
.PHONY : src/hyperloglog.c.i

src/hyperloglog.s: src/hyperloglog.c.s

.PHONY : src/hyperloglog.s

# target to generate assembly for a file
src/hyperloglog.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/hyperloglog.c.s
.PHONY : src/hyperloglog.c.s

src/intset.o: src/intset.c.o

.PHONY : src/intset.o

# target to build an object file
src/intset.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/intset.c.o
.PHONY : src/intset.c.o

src/intset.i: src/intset.c.i

.PHONY : src/intset.i

# target to preprocess a source file
src/intset.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/intset.c.i
.PHONY : src/intset.c.i

src/intset.s: src/intset.c.s

.PHONY : src/intset.s

# target to generate assembly for a file
src/intset.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/intset.c.s
.PHONY : src/intset.c.s

src/latency.o: src/latency.c.o

.PHONY : src/latency.o

# target to build an object file
src/latency.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/latency.c.o
.PHONY : src/latency.c.o

src/latency.i: src/latency.c.i

.PHONY : src/latency.i

# target to preprocess a source file
src/latency.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/latency.c.i
.PHONY : src/latency.c.i

src/latency.s: src/latency.c.s

.PHONY : src/latency.s

# target to generate assembly for a file
src/latency.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/latency.c.s
.PHONY : src/latency.c.s

src/lazyfree.o: src/lazyfree.c.o

.PHONY : src/lazyfree.o

# target to build an object file
src/lazyfree.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lazyfree.c.o
.PHONY : src/lazyfree.c.o

src/lazyfree.i: src/lazyfree.c.i

.PHONY : src/lazyfree.i

# target to preprocess a source file
src/lazyfree.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lazyfree.c.i
.PHONY : src/lazyfree.c.i

src/lazyfree.s: src/lazyfree.c.s

.PHONY : src/lazyfree.s

# target to generate assembly for a file
src/lazyfree.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lazyfree.c.s
.PHONY : src/lazyfree.c.s

src/listpack.o: src/listpack.c.o

.PHONY : src/listpack.o

# target to build an object file
src/listpack.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/listpack.c.o
.PHONY : src/listpack.c.o

src/listpack.i: src/listpack.c.i

.PHONY : src/listpack.i

# target to preprocess a source file
src/listpack.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/listpack.c.i
.PHONY : src/listpack.c.i

src/listpack.s: src/listpack.c.s

.PHONY : src/listpack.s

# target to generate assembly for a file
src/listpack.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/listpack.c.s
.PHONY : src/listpack.c.s

src/localtime.o: src/localtime.c.o

.PHONY : src/localtime.o

# target to build an object file
src/localtime.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/localtime.c.o
.PHONY : src/localtime.c.o

src/localtime.i: src/localtime.c.i

.PHONY : src/localtime.i

# target to preprocess a source file
src/localtime.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/localtime.c.i
.PHONY : src/localtime.c.i

src/localtime.s: src/localtime.c.s

.PHONY : src/localtime.s

# target to generate assembly for a file
src/localtime.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/localtime.c.s
.PHONY : src/localtime.c.s

src/lolwut.o: src/lolwut.c.o

.PHONY : src/lolwut.o

# target to build an object file
src/lolwut.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lolwut.c.o
.PHONY : src/lolwut.c.o

src/lolwut.i: src/lolwut.c.i

.PHONY : src/lolwut.i

# target to preprocess a source file
src/lolwut.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lolwut.c.i
.PHONY : src/lolwut.c.i

src/lolwut.s: src/lolwut.c.s

.PHONY : src/lolwut.s

# target to generate assembly for a file
src/lolwut.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lolwut.c.s
.PHONY : src/lolwut.c.s

src/lolwut5.o: src/lolwut5.c.o

.PHONY : src/lolwut5.o

# target to build an object file
src/lolwut5.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lolwut5.c.o
.PHONY : src/lolwut5.c.o

src/lolwut5.i: src/lolwut5.c.i

.PHONY : src/lolwut5.i

# target to preprocess a source file
src/lolwut5.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lolwut5.c.i
.PHONY : src/lolwut5.c.i

src/lolwut5.s: src/lolwut5.c.s

.PHONY : src/lolwut5.s

# target to generate assembly for a file
src/lolwut5.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lolwut5.c.s
.PHONY : src/lolwut5.c.s

src/lzf_c.o: src/lzf_c.c.o

.PHONY : src/lzf_c.o

# target to build an object file
src/lzf_c.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lzf_c.c.o
.PHONY : src/lzf_c.c.o

src/lzf_c.i: src/lzf_c.c.i

.PHONY : src/lzf_c.i

# target to preprocess a source file
src/lzf_c.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lzf_c.c.i
.PHONY : src/lzf_c.c.i

src/lzf_c.s: src/lzf_c.c.s

.PHONY : src/lzf_c.s

# target to generate assembly for a file
src/lzf_c.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lzf_c.c.s
.PHONY : src/lzf_c.c.s

src/lzf_d.o: src/lzf_d.c.o

.PHONY : src/lzf_d.o

# target to build an object file
src/lzf_d.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lzf_d.c.o
.PHONY : src/lzf_d.c.o

src/lzf_d.i: src/lzf_d.c.i

.PHONY : src/lzf_d.i

# target to preprocess a source file
src/lzf_d.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lzf_d.c.i
.PHONY : src/lzf_d.c.i

src/lzf_d.s: src/lzf_d.c.s

.PHONY : src/lzf_d.s

# target to generate assembly for a file
src/lzf_d.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/lzf_d.c.s
.PHONY : src/lzf_d.c.s

src/memtest.o: src/memtest.c.o

.PHONY : src/memtest.o

# target to build an object file
src/memtest.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/memtest.c.o
.PHONY : src/memtest.c.o

src/memtest.i: src/memtest.c.i

.PHONY : src/memtest.i

# target to preprocess a source file
src/memtest.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/memtest.c.i
.PHONY : src/memtest.c.i

src/memtest.s: src/memtest.c.s

.PHONY : src/memtest.s

# target to generate assembly for a file
src/memtest.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/memtest.c.s
.PHONY : src/memtest.c.s

src/module.o: src/module.c.o

.PHONY : src/module.o

# target to build an object file
src/module.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/module.c.o
.PHONY : src/module.c.o

src/module.i: src/module.c.i

.PHONY : src/module.i

# target to preprocess a source file
src/module.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/module.c.i
.PHONY : src/module.c.i

src/module.s: src/module.c.s

.PHONY : src/module.s

# target to generate assembly for a file
src/module.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/module.c.s
.PHONY : src/module.c.s

src/multi.o: src/multi.c.o

.PHONY : src/multi.o

# target to build an object file
src/multi.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/multi.c.o
.PHONY : src/multi.c.o

src/multi.i: src/multi.c.i

.PHONY : src/multi.i

# target to preprocess a source file
src/multi.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/multi.c.i
.PHONY : src/multi.c.i

src/multi.s: src/multi.c.s

.PHONY : src/multi.s

# target to generate assembly for a file
src/multi.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/multi.c.s
.PHONY : src/multi.c.s

src/networking.o: src/networking.c.o

.PHONY : src/networking.o

# target to build an object file
src/networking.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/networking.c.o
.PHONY : src/networking.c.o

src/networking.i: src/networking.c.i

.PHONY : src/networking.i

# target to preprocess a source file
src/networking.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/networking.c.i
.PHONY : src/networking.c.i

src/networking.s: src/networking.c.s

.PHONY : src/networking.s

# target to generate assembly for a file
src/networking.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/networking.c.s
.PHONY : src/networking.c.s

src/notify.o: src/notify.c.o

.PHONY : src/notify.o

# target to build an object file
src/notify.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/notify.c.o
.PHONY : src/notify.c.o

src/notify.i: src/notify.c.i

.PHONY : src/notify.i

# target to preprocess a source file
src/notify.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/notify.c.i
.PHONY : src/notify.c.i

src/notify.s: src/notify.c.s

.PHONY : src/notify.s

# target to generate assembly for a file
src/notify.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/notify.c.s
.PHONY : src/notify.c.s

src/object.o: src/object.c.o

.PHONY : src/object.o

# target to build an object file
src/object.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/object.c.o
.PHONY : src/object.c.o

src/object.i: src/object.c.i

.PHONY : src/object.i

# target to preprocess a source file
src/object.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/object.c.i
.PHONY : src/object.c.i

src/object.s: src/object.c.s

.PHONY : src/object.s

# target to generate assembly for a file
src/object.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/object.c.s
.PHONY : src/object.c.s

src/pqsort.o: src/pqsort.c.o

.PHONY : src/pqsort.o

# target to build an object file
src/pqsort.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/pqsort.c.o
.PHONY : src/pqsort.c.o

src/pqsort.i: src/pqsort.c.i

.PHONY : src/pqsort.i

# target to preprocess a source file
src/pqsort.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/pqsort.c.i
.PHONY : src/pqsort.c.i

src/pqsort.s: src/pqsort.c.s

.PHONY : src/pqsort.s

# target to generate assembly for a file
src/pqsort.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/pqsort.c.s
.PHONY : src/pqsort.c.s

src/pubsub.o: src/pubsub.c.o

.PHONY : src/pubsub.o

# target to build an object file
src/pubsub.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/pubsub.c.o
.PHONY : src/pubsub.c.o

src/pubsub.i: src/pubsub.c.i

.PHONY : src/pubsub.i

# target to preprocess a source file
src/pubsub.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/pubsub.c.i
.PHONY : src/pubsub.c.i

src/pubsub.s: src/pubsub.c.s

.PHONY : src/pubsub.s

# target to generate assembly for a file
src/pubsub.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/pubsub.c.s
.PHONY : src/pubsub.c.s

src/quicklist.o: src/quicklist.c.o

.PHONY : src/quicklist.o

# target to build an object file
src/quicklist.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/quicklist.c.o
.PHONY : src/quicklist.c.o

src/quicklist.i: src/quicklist.c.i

.PHONY : src/quicklist.i

# target to preprocess a source file
src/quicklist.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/quicklist.c.i
.PHONY : src/quicklist.c.i

src/quicklist.s: src/quicklist.c.s

.PHONY : src/quicklist.s

# target to generate assembly for a file
src/quicklist.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/quicklist.c.s
.PHONY : src/quicklist.c.s

src/rand.o: src/rand.c.o

.PHONY : src/rand.o

# target to build an object file
src/rand.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rand.c.o
.PHONY : src/rand.c.o

src/rand.i: src/rand.c.i

.PHONY : src/rand.i

# target to preprocess a source file
src/rand.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rand.c.i
.PHONY : src/rand.c.i

src/rand.s: src/rand.c.s

.PHONY : src/rand.s

# target to generate assembly for a file
src/rand.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rand.c.s
.PHONY : src/rand.c.s

src/rax.o: src/rax.c.o

.PHONY : src/rax.o

# target to build an object file
src/rax.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rax.c.o
.PHONY : src/rax.c.o

src/rax.i: src/rax.c.i

.PHONY : src/rax.i

# target to preprocess a source file
src/rax.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rax.c.i
.PHONY : src/rax.c.i

src/rax.s: src/rax.c.s

.PHONY : src/rax.s

# target to generate assembly for a file
src/rax.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rax.c.s
.PHONY : src/rax.c.s

src/rdb.o: src/rdb.c.o

.PHONY : src/rdb.o

# target to build an object file
src/rdb.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rdb.c.o
.PHONY : src/rdb.c.o

src/rdb.i: src/rdb.c.i

.PHONY : src/rdb.i

# target to preprocess a source file
src/rdb.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rdb.c.i
.PHONY : src/rdb.c.i

src/rdb.s: src/rdb.c.s

.PHONY : src/rdb.s

# target to generate assembly for a file
src/rdb.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rdb.c.s
.PHONY : src/rdb.c.s

src/redis-check-aof.o: src/redis-check-aof.c.o

.PHONY : src/redis-check-aof.o

# target to build an object file
src/redis-check-aof.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/redis-check-aof.c.o
.PHONY : src/redis-check-aof.c.o

src/redis-check-aof.i: src/redis-check-aof.c.i

.PHONY : src/redis-check-aof.i

# target to preprocess a source file
src/redis-check-aof.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/redis-check-aof.c.i
.PHONY : src/redis-check-aof.c.i

src/redis-check-aof.s: src/redis-check-aof.c.s

.PHONY : src/redis-check-aof.s

# target to generate assembly for a file
src/redis-check-aof.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/redis-check-aof.c.s
.PHONY : src/redis-check-aof.c.s

src/redis-check-rdb.o: src/redis-check-rdb.c.o

.PHONY : src/redis-check-rdb.o

# target to build an object file
src/redis-check-rdb.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/redis-check-rdb.c.o
.PHONY : src/redis-check-rdb.c.o

src/redis-check-rdb.i: src/redis-check-rdb.c.i

.PHONY : src/redis-check-rdb.i

# target to preprocess a source file
src/redis-check-rdb.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/redis-check-rdb.c.i
.PHONY : src/redis-check-rdb.c.i

src/redis-check-rdb.s: src/redis-check-rdb.c.s

.PHONY : src/redis-check-rdb.s

# target to generate assembly for a file
src/redis-check-rdb.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/redis-check-rdb.c.s
.PHONY : src/redis-check-rdb.c.s

src/redis-cli.o: src/redis-cli.c.o

.PHONY : src/redis-cli.o

# target to build an object file
src/redis-cli.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/redis-cli.c.o
.PHONY : src/redis-cli.c.o

src/redis-cli.i: src/redis-cli.c.i

.PHONY : src/redis-cli.i

# target to preprocess a source file
src/redis-cli.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/redis-cli.c.i
.PHONY : src/redis-cli.c.i

src/redis-cli.s: src/redis-cli.c.s

.PHONY : src/redis-cli.s

# target to generate assembly for a file
src/redis-cli.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/redis-cli.c.s
.PHONY : src/redis-cli.c.s

src/release.o: src/release.c.o

.PHONY : src/release.o

# target to build an object file
src/release.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/release.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/release.c.o
.PHONY : src/release.c.o

src/release.i: src/release.c.i

.PHONY : src/release.i

# target to preprocess a source file
src/release.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/release.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/release.c.i
.PHONY : src/release.c.i

src/release.s: src/release.c.s

.PHONY : src/release.s

# target to generate assembly for a file
src/release.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/release.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/release.c.s
.PHONY : src/release.c.s

src/replication.o: src/replication.c.o

.PHONY : src/replication.o

# target to build an object file
src/replication.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/replication.c.o
.PHONY : src/replication.c.o

src/replication.i: src/replication.c.i

.PHONY : src/replication.i

# target to preprocess a source file
src/replication.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/replication.c.i
.PHONY : src/replication.c.i

src/replication.s: src/replication.c.s

.PHONY : src/replication.s

# target to generate assembly for a file
src/replication.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/replication.c.s
.PHONY : src/replication.c.s

src/rio.o: src/rio.c.o

.PHONY : src/rio.o

# target to build an object file
src/rio.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rio.c.o
.PHONY : src/rio.c.o

src/rio.i: src/rio.c.i

.PHONY : src/rio.i

# target to preprocess a source file
src/rio.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rio.c.i
.PHONY : src/rio.c.i

src/rio.s: src/rio.c.s

.PHONY : src/rio.s

# target to generate assembly for a file
src/rio.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/rio.c.s
.PHONY : src/rio.c.s

src/scripting.o: src/scripting.c.o

.PHONY : src/scripting.o

# target to build an object file
src/scripting.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/scripting.c.o
.PHONY : src/scripting.c.o

src/scripting.i: src/scripting.c.i

.PHONY : src/scripting.i

# target to preprocess a source file
src/scripting.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/scripting.c.i
.PHONY : src/scripting.c.i

src/scripting.s: src/scripting.c.s

.PHONY : src/scripting.s

# target to generate assembly for a file
src/scripting.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/scripting.c.s
.PHONY : src/scripting.c.s

src/sds.o: src/sds.c.o

.PHONY : src/sds.o

# target to build an object file
src/sds.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/sds.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sds.c.o
.PHONY : src/sds.c.o

src/sds.i: src/sds.c.i

.PHONY : src/sds.i

# target to preprocess a source file
src/sds.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/sds.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sds.c.i
.PHONY : src/sds.c.i

src/sds.s: src/sds.c.s

.PHONY : src/sds.s

# target to generate assembly for a file
src/sds.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/sds.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sds.c.s
.PHONY : src/sds.c.s

src/sentinel.o: src/sentinel.c.o

.PHONY : src/sentinel.o

# target to build an object file
src/sentinel.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sentinel.c.o
.PHONY : src/sentinel.c.o

src/sentinel.i: src/sentinel.c.i

.PHONY : src/sentinel.i

# target to preprocess a source file
src/sentinel.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sentinel.c.i
.PHONY : src/sentinel.c.i

src/sentinel.s: src/sentinel.c.s

.PHONY : src/sentinel.s

# target to generate assembly for a file
src/sentinel.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sentinel.c.s
.PHONY : src/sentinel.c.s

src/server.o: src/server.c.o

.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/server.c.s
.PHONY : src/server.c.s

src/setproctitle.o: src/setproctitle.c.o

.PHONY : src/setproctitle.o

# target to build an object file
src/setproctitle.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/setproctitle.c.o
.PHONY : src/setproctitle.c.o

src/setproctitle.i: src/setproctitle.c.i

.PHONY : src/setproctitle.i

# target to preprocess a source file
src/setproctitle.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/setproctitle.c.i
.PHONY : src/setproctitle.c.i

src/setproctitle.s: src/setproctitle.c.s

.PHONY : src/setproctitle.s

# target to generate assembly for a file
src/setproctitle.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/setproctitle.c.s
.PHONY : src/setproctitle.c.s

src/sha1.o: src/sha1.c.o

.PHONY : src/sha1.o

# target to build an object file
src/sha1.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sha1.c.o
.PHONY : src/sha1.c.o

src/sha1.i: src/sha1.c.i

.PHONY : src/sha1.i

# target to preprocess a source file
src/sha1.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sha1.c.i
.PHONY : src/sha1.c.i

src/sha1.s: src/sha1.c.s

.PHONY : src/sha1.s

# target to generate assembly for a file
src/sha1.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sha1.c.s
.PHONY : src/sha1.c.s

src/sha256.o: src/sha256.c.o

.PHONY : src/sha256.o

# target to build an object file
src/sha256.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sha256.c.o
.PHONY : src/sha256.c.o

src/sha256.i: src/sha256.c.i

.PHONY : src/sha256.i

# target to preprocess a source file
src/sha256.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sha256.c.i
.PHONY : src/sha256.c.i

src/sha256.s: src/sha256.c.s

.PHONY : src/sha256.s

# target to generate assembly for a file
src/sha256.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sha256.c.s
.PHONY : src/sha256.c.s

src/siphash.o: src/siphash.c.o

.PHONY : src/siphash.o

# target to build an object file
src/siphash.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/siphash.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/siphash.c.o
.PHONY : src/siphash.c.o

src/siphash.i: src/siphash.c.i

.PHONY : src/siphash.i

# target to preprocess a source file
src/siphash.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/siphash.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/siphash.c.i
.PHONY : src/siphash.c.i

src/siphash.s: src/siphash.c.s

.PHONY : src/siphash.s

# target to generate assembly for a file
src/siphash.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/siphash.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/siphash.c.s
.PHONY : src/siphash.c.s

src/slowlog.o: src/slowlog.c.o

.PHONY : src/slowlog.o

# target to build an object file
src/slowlog.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/slowlog.c.o
.PHONY : src/slowlog.c.o

src/slowlog.i: src/slowlog.c.i

.PHONY : src/slowlog.i

# target to preprocess a source file
src/slowlog.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/slowlog.c.i
.PHONY : src/slowlog.c.i

src/slowlog.s: src/slowlog.c.s

.PHONY : src/slowlog.s

# target to generate assembly for a file
src/slowlog.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/slowlog.c.s
.PHONY : src/slowlog.c.s

src/sort.o: src/sort.c.o

.PHONY : src/sort.o

# target to build an object file
src/sort.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sort.c.o
.PHONY : src/sort.c.o

src/sort.i: src/sort.c.i

.PHONY : src/sort.i

# target to preprocess a source file
src/sort.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sort.c.i
.PHONY : src/sort.c.i

src/sort.s: src/sort.c.s

.PHONY : src/sort.s

# target to generate assembly for a file
src/sort.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sort.c.s
.PHONY : src/sort.c.s

src/sparkline.o: src/sparkline.c.o

.PHONY : src/sparkline.o

# target to build an object file
src/sparkline.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sparkline.c.o
.PHONY : src/sparkline.c.o

src/sparkline.i: src/sparkline.c.i

.PHONY : src/sparkline.i

# target to preprocess a source file
src/sparkline.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sparkline.c.i
.PHONY : src/sparkline.c.i

src/sparkline.s: src/sparkline.c.s

.PHONY : src/sparkline.s

# target to generate assembly for a file
src/sparkline.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/sparkline.c.s
.PHONY : src/sparkline.c.s

src/syncio.o: src/syncio.c.o

.PHONY : src/syncio.o

# target to build an object file
src/syncio.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/syncio.c.o
.PHONY : src/syncio.c.o

src/syncio.i: src/syncio.c.i

.PHONY : src/syncio.i

# target to preprocess a source file
src/syncio.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/syncio.c.i
.PHONY : src/syncio.c.i

src/syncio.s: src/syncio.c.s

.PHONY : src/syncio.s

# target to generate assembly for a file
src/syncio.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/syncio.c.s
.PHONY : src/syncio.c.s

src/t_hash.o: src/t_hash.c.o

.PHONY : src/t_hash.o

# target to build an object file
src/t_hash.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_hash.c.o
.PHONY : src/t_hash.c.o

src/t_hash.i: src/t_hash.c.i

.PHONY : src/t_hash.i

# target to preprocess a source file
src/t_hash.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_hash.c.i
.PHONY : src/t_hash.c.i

src/t_hash.s: src/t_hash.c.s

.PHONY : src/t_hash.s

# target to generate assembly for a file
src/t_hash.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_hash.c.s
.PHONY : src/t_hash.c.s

src/t_list.o: src/t_list.c.o

.PHONY : src/t_list.o

# target to build an object file
src/t_list.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_list.c.o
.PHONY : src/t_list.c.o

src/t_list.i: src/t_list.c.i

.PHONY : src/t_list.i

# target to preprocess a source file
src/t_list.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_list.c.i
.PHONY : src/t_list.c.i

src/t_list.s: src/t_list.c.s

.PHONY : src/t_list.s

# target to generate assembly for a file
src/t_list.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_list.c.s
.PHONY : src/t_list.c.s

src/t_set.o: src/t_set.c.o

.PHONY : src/t_set.o

# target to build an object file
src/t_set.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_set.c.o
.PHONY : src/t_set.c.o

src/t_set.i: src/t_set.c.i

.PHONY : src/t_set.i

# target to preprocess a source file
src/t_set.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_set.c.i
.PHONY : src/t_set.c.i

src/t_set.s: src/t_set.c.s

.PHONY : src/t_set.s

# target to generate assembly for a file
src/t_set.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_set.c.s
.PHONY : src/t_set.c.s

src/t_stream.o: src/t_stream.c.o

.PHONY : src/t_stream.o

# target to build an object file
src/t_stream.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_stream.c.o
.PHONY : src/t_stream.c.o

src/t_stream.i: src/t_stream.c.i

.PHONY : src/t_stream.i

# target to preprocess a source file
src/t_stream.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_stream.c.i
.PHONY : src/t_stream.c.i

src/t_stream.s: src/t_stream.c.s

.PHONY : src/t_stream.s

# target to generate assembly for a file
src/t_stream.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_stream.c.s
.PHONY : src/t_stream.c.s

src/t_string.o: src/t_string.c.o

.PHONY : src/t_string.o

# target to build an object file
src/t_string.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_string.c.o
.PHONY : src/t_string.c.o

src/t_string.i: src/t_string.c.i

.PHONY : src/t_string.i

# target to preprocess a source file
src/t_string.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_string.c.i
.PHONY : src/t_string.c.i

src/t_string.s: src/t_string.c.s

.PHONY : src/t_string.s

# target to generate assembly for a file
src/t_string.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_string.c.s
.PHONY : src/t_string.c.s

src/t_zset.o: src/t_zset.c.o

.PHONY : src/t_zset.o

# target to build an object file
src/t_zset.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_zset.c.o
.PHONY : src/t_zset.c.o

src/t_zset.i: src/t_zset.c.i

.PHONY : src/t_zset.i

# target to preprocess a source file
src/t_zset.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_zset.c.i
.PHONY : src/t_zset.c.i

src/t_zset.s: src/t_zset.c.s

.PHONY : src/t_zset.s

# target to generate assembly for a file
src/t_zset.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/t_zset.c.s
.PHONY : src/t_zset.c.s

src/tracking.o: src/tracking.c.o

.PHONY : src/tracking.o

# target to build an object file
src/tracking.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/tracking.c.o
.PHONY : src/tracking.c.o

src/tracking.i: src/tracking.c.i

.PHONY : src/tracking.i

# target to preprocess a source file
src/tracking.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/tracking.c.i
.PHONY : src/tracking.c.i

src/tracking.s: src/tracking.c.s

.PHONY : src/tracking.s

# target to generate assembly for a file
src/tracking.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/tracking.c.s
.PHONY : src/tracking.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/util.c.s
.PHONY : src/util.c.s

src/ziplist.o: src/ziplist.c.o

.PHONY : src/ziplist.o

# target to build an object file
src/ziplist.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ziplist.c.o
.PHONY : src/ziplist.c.o

src/ziplist.i: src/ziplist.c.i

.PHONY : src/ziplist.i

# target to preprocess a source file
src/ziplist.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ziplist.c.i
.PHONY : src/ziplist.c.i

src/ziplist.s: src/ziplist.c.s

.PHONY : src/ziplist.s

# target to generate assembly for a file
src/ziplist.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/ziplist.c.s
.PHONY : src/ziplist.c.s

src/zipmap.o: src/zipmap.c.o

.PHONY : src/zipmap.o

# target to build an object file
src/zipmap.c.o:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/zipmap.c.o
.PHONY : src/zipmap.c.o

src/zipmap.i: src/zipmap.c.i

.PHONY : src/zipmap.i

# target to preprocess a source file
src/zipmap.c.i:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/zipmap.c.i
.PHONY : src/zipmap.c.i

src/zipmap.s: src/zipmap.c.s

.PHONY : src/zipmap.s

# target to generate assembly for a file
src/zipmap.c.s:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/zipmap.c.s
.PHONY : src/zipmap.c.s

src/zmalloc.o: src/zmalloc.c.o

.PHONY : src/zmalloc.o

# target to build an object file
src/zmalloc.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/zmalloc.c.o
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/zmalloc.c.o
.PHONY : src/zmalloc.c.o

src/zmalloc.i: src/zmalloc.c.i

.PHONY : src/zmalloc.i

# target to preprocess a source file
src/zmalloc.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/zmalloc.c.i
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/zmalloc.c.i
.PHONY : src/zmalloc.c.i

src/zmalloc.s: src/zmalloc.c.s

.PHONY : src/zmalloc.s

# target to generate assembly for a file
src/zmalloc.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/zmalloc.c.s
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/src/zmalloc.c.s
.PHONY : src/zmalloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... redis-cli"
	@echo "... redis-server"
	@echo "... hiredis"
	@echo "... linenoise"
	@echo "... lua"
	@echo "... testmodule"
	@echo "... helloblock"
	@echo "... hellotype"
	@echo "... helloworld"
	@echo "... src/acl.o"
	@echo "... src/acl.i"
	@echo "... src/acl.s"
	@echo "... src/adlist.o"
	@echo "... src/adlist.i"
	@echo "... src/adlist.s"
	@echo "... src/ae.o"
	@echo "... src/ae.i"
	@echo "... src/ae.s"
	@echo "... src/ae_kqueue.o"
	@echo "... src/ae_kqueue.i"
	@echo "... src/ae_kqueue.s"
	@echo "... src/anet.o"
	@echo "... src/anet.i"
	@echo "... src/anet.s"
	@echo "... src/aof.o"
	@echo "... src/aof.i"
	@echo "... src/aof.s"
	@echo "... src/bio.o"
	@echo "... src/bio.i"
	@echo "... src/bio.s"
	@echo "... src/bitops.o"
	@echo "... src/bitops.i"
	@echo "... src/bitops.s"
	@echo "... src/blocked.o"
	@echo "... src/blocked.i"
	@echo "... src/blocked.s"
	@echo "... src/childinfo.o"
	@echo "... src/childinfo.i"
	@echo "... src/childinfo.s"
	@echo "... src/cluster.o"
	@echo "... src/cluster.i"
	@echo "... src/cluster.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/crc16.o"
	@echo "... src/crc16.i"
	@echo "... src/crc16.s"
	@echo "... src/crc64.o"
	@echo "... src/crc64.i"
	@echo "... src/crc64.s"
	@echo "... src/db.o"
	@echo "... src/db.i"
	@echo "... src/db.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/defrag.o"
	@echo "... src/defrag.i"
	@echo "... src/defrag.s"
	@echo "... src/dict.o"
	@echo "... src/dict.i"
	@echo "... src/dict.s"
	@echo "... src/endianconv.o"
	@echo "... src/endianconv.i"
	@echo "... src/endianconv.s"
	@echo "... src/evict.o"
	@echo "... src/evict.i"
	@echo "... src/evict.s"
	@echo "... src/expire.o"
	@echo "... src/expire.i"
	@echo "... src/expire.s"
	@echo "... src/geo.o"
	@echo "... src/geo.i"
	@echo "... src/geo.s"
	@echo "... src/geohash.o"
	@echo "... src/geohash.i"
	@echo "... src/geohash.s"
	@echo "... src/geohash_helper.o"
	@echo "... src/geohash_helper.i"
	@echo "... src/geohash_helper.s"
	@echo "... src/gopher.o"
	@echo "... src/gopher.i"
	@echo "... src/gopher.s"
	@echo "... src/hyperloglog.o"
	@echo "... src/hyperloglog.i"
	@echo "... src/hyperloglog.s"
	@echo "... src/intset.o"
	@echo "... src/intset.i"
	@echo "... src/intset.s"
	@echo "... src/latency.o"
	@echo "... src/latency.i"
	@echo "... src/latency.s"
	@echo "... src/lazyfree.o"
	@echo "... src/lazyfree.i"
	@echo "... src/lazyfree.s"
	@echo "... src/listpack.o"
	@echo "... src/listpack.i"
	@echo "... src/listpack.s"
	@echo "... src/localtime.o"
	@echo "... src/localtime.i"
	@echo "... src/localtime.s"
	@echo "... src/lolwut.o"
	@echo "... src/lolwut.i"
	@echo "... src/lolwut.s"
	@echo "... src/lolwut5.o"
	@echo "... src/lolwut5.i"
	@echo "... src/lolwut5.s"
	@echo "... src/lzf_c.o"
	@echo "... src/lzf_c.i"
	@echo "... src/lzf_c.s"
	@echo "... src/lzf_d.o"
	@echo "... src/lzf_d.i"
	@echo "... src/lzf_d.s"
	@echo "... src/memtest.o"
	@echo "... src/memtest.i"
	@echo "... src/memtest.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/multi.o"
	@echo "... src/multi.i"
	@echo "... src/multi.s"
	@echo "... src/networking.o"
	@echo "... src/networking.i"
	@echo "... src/networking.s"
	@echo "... src/notify.o"
	@echo "... src/notify.i"
	@echo "... src/notify.s"
	@echo "... src/object.o"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/pqsort.o"
	@echo "... src/pqsort.i"
	@echo "... src/pqsort.s"
	@echo "... src/pubsub.o"
	@echo "... src/pubsub.i"
	@echo "... src/pubsub.s"
	@echo "... src/quicklist.o"
	@echo "... src/quicklist.i"
	@echo "... src/quicklist.s"
	@echo "... src/rand.o"
	@echo "... src/rand.i"
	@echo "... src/rand.s"
	@echo "... src/rax.o"
	@echo "... src/rax.i"
	@echo "... src/rax.s"
	@echo "... src/rdb.o"
	@echo "... src/rdb.i"
	@echo "... src/rdb.s"
	@echo "... src/redis-check-aof.o"
	@echo "... src/redis-check-aof.i"
	@echo "... src/redis-check-aof.s"
	@echo "... src/redis-check-rdb.o"
	@echo "... src/redis-check-rdb.i"
	@echo "... src/redis-check-rdb.s"
	@echo "... src/redis-cli.o"
	@echo "... src/redis-cli.i"
	@echo "... src/redis-cli.s"
	@echo "... src/release.o"
	@echo "... src/release.i"
	@echo "... src/release.s"
	@echo "... src/replication.o"
	@echo "... src/replication.i"
	@echo "... src/replication.s"
	@echo "... src/rio.o"
	@echo "... src/rio.i"
	@echo "... src/rio.s"
	@echo "... src/scripting.o"
	@echo "... src/scripting.i"
	@echo "... src/scripting.s"
	@echo "... src/sds.o"
	@echo "... src/sds.i"
	@echo "... src/sds.s"
	@echo "... src/sentinel.o"
	@echo "... src/sentinel.i"
	@echo "... src/sentinel.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/setproctitle.o"
	@echo "... src/setproctitle.i"
	@echo "... src/setproctitle.s"
	@echo "... src/sha1.o"
	@echo "... src/sha1.i"
	@echo "... src/sha1.s"
	@echo "... src/sha256.o"
	@echo "... src/sha256.i"
	@echo "... src/sha256.s"
	@echo "... src/siphash.o"
	@echo "... src/siphash.i"
	@echo "... src/siphash.s"
	@echo "... src/slowlog.o"
	@echo "... src/slowlog.i"
	@echo "... src/slowlog.s"
	@echo "... src/sort.o"
	@echo "... src/sort.i"
	@echo "... src/sort.s"
	@echo "... src/sparkline.o"
	@echo "... src/sparkline.i"
	@echo "... src/sparkline.s"
	@echo "... src/syncio.o"
	@echo "... src/syncio.i"
	@echo "... src/syncio.s"
	@echo "... src/t_hash.o"
	@echo "... src/t_hash.i"
	@echo "... src/t_hash.s"
	@echo "... src/t_list.o"
	@echo "... src/t_list.i"
	@echo "... src/t_list.s"
	@echo "... src/t_set.o"
	@echo "... src/t_set.i"
	@echo "... src/t_set.s"
	@echo "... src/t_stream.o"
	@echo "... src/t_stream.i"
	@echo "... src/t_stream.s"
	@echo "... src/t_string.o"
	@echo "... src/t_string.i"
	@echo "... src/t_string.s"
	@echo "... src/t_zset.o"
	@echo "... src/t_zset.i"
	@echo "... src/t_zset.s"
	@echo "... src/tracking.o"
	@echo "... src/tracking.i"
	@echo "... src/tracking.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/ziplist.o"
	@echo "... src/ziplist.i"
	@echo "... src/ziplist.s"
	@echo "... src/zipmap.o"
	@echo "... src/zipmap.i"
	@echo "... src/zipmap.s"
	@echo "... src/zmalloc.o"
	@echo "... src/zmalloc.i"
	@echo "... src/zmalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

