# Top level makefile, the real stuff is at ./src/Makefile and in ./modules/Makefile
#
# Auto-detects cloned modules (via utils/modules/update-modules.sh) and builds
# them alongside Redis core.  Use `make core` to build Redis without modules.

# Auto-detect which modules have been cloned (have a src/ directory)
MODULE_NAMES := redisjson redistimeseries redisbloom redisearch
AVAILABLE_MODULES := $(foreach m,$(MODULE_NAMES),$(if $(wildcard modules/$(m)/src/Makefile),$(m)))
HAS_MODULES := $(if $(AVAILABLE_MODULES),yes,no)

# Allow explicit override
ifeq ($(BUILD_WITH_MODULES), no)
	HAS_MODULES := no
	AVAILABLE_MODULES :=
endif

# Never build modules on 32-bit
ifeq ($(MAKECMDGOALS),32bit)
	HAS_MODULES := no
	AVAILABLE_MODULES :=
endif

default: all

# Build everything: Redis core + any available modules
all:
	$(MAKE) -C src all
ifeq ($(HAS_MODULES),yes)
	$(MAKE) -C modules all
endif

# Build Redis core only (no modules)
core:
	$(MAKE) -C src all

.DEFAULT:
	set -e; for dir in src; do $(MAKE) -C $$dir $@; done
ifeq ($(HAS_MODULES),yes)
	-$(MAKE) -C modules $@ 2>/dev/null || true
endif

install:
	set -e; for dir in src; do $(MAKE) -C $$dir $@; done
ifeq ($(HAS_MODULES),yes)
	$(MAKE) -C modules $@
endif

clean:
	$(MAKE) -C src clean
ifeq ($(HAS_MODULES),yes)
	$(MAKE) -C modules clean
endif

distclean:
	$(MAKE) -C src distclean
ifeq ($(HAS_MODULES),yes)
	$(MAKE) -C modules distclean
endif

# Run Redis server with all available modules loaded (deterministic order)
MODULE_LOAD_ORDER := redisjson redistimeseries redisbloom redisearch
run: all
	@LOADMODULES=""; \
	for name in $(MODULE_LOAD_ORDER); do \
		so=$$(find modules/$${name} -maxdepth 1 -name '*.so' 2>/dev/null | head -1); \
		if [ -n "$${so}" ]; then \
			LOADMODULES="$${LOADMODULES} --loadmodule $${so}"; \
		fi; \
	done; \
	if [ -n "$${LOADMODULES}" ]; then \
		echo "Starting Redis with modules:$${LOADMODULES}"; \
	else \
		echo "Starting Redis (no modules found)"; \
	fi; \
	./src/redis-server $${LOADMODULES}

# Run Redis with redis-full.conf (generated by update-modules.sh)
run-full: all
	@if [ ! -f redis-full.conf ]; then \
		echo "redis-full.conf not found. Run 'utils/modules/update-modules.sh' first."; \
		exit 1; \
	fi; \
	echo "Starting Redis with redis-full.conf"; \
	./src/redis-server redis-full.conf

# Clone/update all module sources and generate redis-full.conf
update-modules:
	./utils/modules/update-modules.sh

# Clone/update modules without installing dependencies
update-modules-no-deps:
	./utils/modules/update-modules.sh --skip-deps

# Run Redis core tests
test:
	./runtest

# Run all tests including module tests
test-all: test
	./runtest-moduleapi

.PHONY: default all core install clean distclean run run-full update-modules update-modules-no-deps test test-all
