#!/bin/sh
TCL_VERSIONS="8.5 8.6"
TCLSH=""

for VERSION in $TCL_VERSIONS; do
	TCL=`which tclsh$VERSION 2>/dev/null` && TCLSH=$TCL
done

if [ -z $TCLSH ]
then
    echo "You need tcl 8.5 or newer in order to run the Redis test"
    exit 1
fi

if [ "$BUILD_ARCH" = "" ]
then
  echo "You need to specify BUILD_ARCH to determine what version to test"
  exit 1
fi

ln -sf obj.${BUILD_ARCH}/redis-server src/redis-server
ln -sf obj.${BUILD_ARCH}/redis-check-aof src/redis-check-aof

$TCLSH tests/test_helper.tcl $*

rm src/redis-server
rm src/redis-check-aof
