#!/bin/sh
# Most tests assume running from the project root
cd "C:/Users/samue/repos/redis"
export REDIS_BIN_DIR="C:/Users/samue/repos/redis/bin/Release"
# Most tests assume running from the project root
cd "C:/Users/samue/repos/redis"
export REDIS_BIN_DIR="C:/Users/samue/repos/redis/bin/Release"
TCL_VERSIONS="8.5 8.6 8.7 9.0"
TCLSH=""

for VERSION in $TCL_VERSIONS; do
	TCL=`which tclsh 2>/dev/null` && TCLSH=$TCL
done

if [ -z $TCLSH ]
then
    echo "You need tcl 8.5 or newer in order to run the Redis Cluster test"
    exit 1
fi
$TCLSH tests/cluster/run.tcl $*
