SRC_DIR = src
MODULE_VERSION = v8.7.90
MODULE_REPO = https://github.com/redisearch/redisearch
TARGET_MODULE = $(SRC_DIR)/bin/$(FULL_VARIANT)/search-community/redisearch.so
MODULE_BUILD_ARGS = CXX_SVE2=OFF

include ../common.mk
