.TH REDIS-CLI 1 "January 13, 2010"
.SH NAME
redis-cli \- Command-line client to redis-server
.SH SYNOPSIS
.B redis-cli
.RI [options]
.SH DESCRIPTION
Redis is a key-value database. It is similar to memcached but the dataset is
not volatile and other datatypes (such as lists and sets) are natively
supported.
.PP
\fBredis-cli\fP provides a simple command-line interface to a Redis server.
.SH OPTIONS
See \fBredis-doc\fP for more information on the commands Redis accepts.
.SH AUTHOR
\fBredis-cli\fP was written by Salvatore Sanfilippo.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
