/*
 * Copyright (c) 2009-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of (a) the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
 */

const char *ascii_logo =
"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ\n"
"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ\n"
"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ		Redis Open Source \n"
"QQQQQQQQQQQQQQQQQQQWQQQQQWWWBBBHHHHHHHHHBWWWQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ		 %s (%s/%d) %s bit\n"
"QQQQQQQQQQQQQQQD!`__ssaaaaaaaaaass_ass_s____.  -~\"\"\?\?9VWQQQQQQQQQQQQQQQQQQQ		Running in %s mode\n"
"QQQQQQQQQQQQQP\'_wmQQQWWBWV\?GwwwmmWQmwwwwwgmZUVVHAqwaaaac,\"\?9$QQQQQQQQQQQQQQ        Port: %d\n"
"QQQQQQQQQQQW! aQWQQQQW\?qw#TTSgwawwggywawwpY\?T\?TYTYTXmwwgZ$ma/-\?4QQQQQQQQQQQ		PID: %ld\n"
"QQQQQQQQQQW\' jQQQQWTqwDYauT9mmwwawww\?WWWWQQQQQ@TT\?TVTT9HQQQQQQw,-4QQQQQQQQQ		Mesugalut!!!\n"
"QQQQQQQQQQ[ jQQQQQyWVw2$wWWQQQWWQWWWW7WQQQQQQQQPWWQQQWQQw7WQQQWWc)WWQQQQQQQ\n"
"QQQQQQQQQf jQQQQQWWmWmmQWU\?\?\?\?\?\?\?9WWQmWQQQQQQQWjWQQQQQQQWQmQQQQWL 4QQQQQQQQ			https://redis.io\n"
"QQQQQQQP\'.yQQQQQQQQQQQP\"       <wa,.!4WQQQQQQQWdWP\?\?!\"\?\?4WWQQQWQQc \?QWQQQQQ\n"
"QQQQQP\'_a.<aamQQQW!<yF \"!` ..  \"\?\?$Qa \"WQQQWTVP\'    \"\?\?\' =QQmWWV\?46/ \?QQQQQ\n"
"QQQP\'sdyWQP\?!`.-\"\?46mQQQQQQT!mQQgaa. <wWQQWQaa _aawmWWQQQQQQQQQWP4a7g -WWQQ\n"
"QQ[ j@mQP\'adQQP4ga, -\?\?\?\?\" <jQQQQQWQQQQQQQQQWW;)WQWWWW9QQP\?\"`  -\?QzQ7L ]QQQ\n"
"QW jQkQ@ jWQQD\'-\?$QQQQQQQQQQQQQQQQQWWQWQQQWQQQc \"4QQQQa   .QP4QQQQfWkl jQQQ\n"
"QE ]QkQk $D\?`  waa \"\?9WWQQQP\?\?T\?47`_aamQQQQQQWWQw,-\?QWWQQQQQ`\"QQQD\\Qf(.QWQQ\n"
"QQ,-Qm4Q/-QmQ6 \"WWQma/  \"\?\?QQQQQQL 4W\"- -\?$QQQQWP`s,awT$QQQ@  \"QW@\?$:.yQQQQ\n"
"QQm/-4wTQgQWQQ,  \?4WWk 4waac -\?\?\?$waQQQQQQQQF\?\?\'<mWWWWWQW\?^  ` ]6QQ\' yQQQQQ\n"
"QQQQw,-\?QmWQQQQw  a,    \?QWWQQQw _.  \"\?\?\?\?9VWaamQWV\?\?\?\"  a j/  ]QQf jQQQQQQ\n"
"QQQQQQw,\"4QQQQQQm,-$Qa     \?\?\?4F jQQQQQwc <aaas _aaaaa 4QW ]E  )WQ`=QQQQQQQ\n"
"QQQQQQWQ/ $QQQQQQQa \?H ]Wwa,     \?\?\?9WWWh dQWWW,=QWWU\?  \?!     )WQ ]QQQQQQQ\n"
"QQQQQQQQQc-QWQQQQQW6,  QWQWQQQk <c                             jWQ ]QQQQQQQ\n"
"QQQQQQQQQQ,\"$WQQWQQQQg,.\"\?QQQQ\'.mQQQmaa,.,                . .; QWQ.]QQQQQQQ\n"
"QQQQQQQQQWQa \?$WQQWQQQQQa,.\"\?( mQQQQQQW[:QQQQm[ ammF jy! j( } jQQQ(:QQQQQQQ\n"
"QQQQQQQQQQWWma \"9gw\?9gdB\?QQwa, -\?\?T$WQQ;:QQQWQ ]WWD _Qf +\?! _jQQQWf QQQQQQQ\n"
"QQQQQQQQQQQQQQQws \"Tqau\?9maZ\?WQmaas,,    --~-- ---  . _ssawmQQQQQQk 3QQQQWQ\n"
"QQQQQQQQQQQQQQQQWQga,-\?9mwad\?1wdT9WQQQQQWVVTTYY\?YTVWQQQQWWD5mQQPQQQ ]QQQQQQ\n"
"QQQQQQQWQQQQQQQQQQQWQQwa,-\?\?$QwadV}<wBHHVHWWBHHUWWBVTTTV5awBQQD6QQQ ]QQQQQQ\n"
"QQQQQQQQQQQQQQQQQQQQQQWWQQga,-\"9$WQQmmwwmBUUHTTVWBWQQQQWVT\?96aQWQQQ ]QQQQQQ\n"
"QQQQQQQQQQWQQQQWQQQQQQQQQQQWQQma,-\?9$QQWWQQQQQQQWmQmmmmmQWQQQQWQQW(.yQQQQQW\n"
"QQQQQQQQQQQQQWQQQQQQWQQQQQQQQQQQQQga%,.  -\?\?9$QQQQQQQQQQQWQQWQQV\? sWQQQQQQQ\n"
"QQQQQQQQQWQQQQQQQQQQQQQQWQQQQQQQQQQQWQQQQmywaa,;~^\"!\?\?\?\?\?\?\?!^`_saQWWQQQQQQQ\n"
"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWWWWQQQQQmwywwwwwwmQQWQQQQQQQQQQQ\n"
"QQQQQQQWQQQWQQQQQQWQQQWQQQQQWQQQQQQQQQQQQQQQQWQQQQQWQQQWWWQQQQQQQQQQQQQQQWQ\n\n";
