/* Automatically generated by generate-command-code.py, do not edit. */

#ifndef __REDIS_HELP_H
#define __REDIS_HELP_H

static char *commandGroups[] = {
    "generic",
    "string",
    "list",
    "set",
    "sorted_set",
    "hash",
    "pubsub",
    "transactions",
    "connection",
    "server",
    "scripting",
    "hyperloglog",
    "cluster",
    "geo",
    "stream",
    "bitmap",
};

struct commandHelp {
    char *name;
    char *params;
    char *summary;
    int group;
    char *since;
} commandHelp[] = {
{"CONFIG SET",
"parameter value",
"Set a configuration parameter to the given value",
0,
"2.0.0"},
{"MIGRATE",
"host port (key|"") destination-db timeout [COPY] [REPLACE] [AUTH password] [AUTH2 username password] [KEYS key [key ...]]",
"Atomically transfer a key from a Redis instance to another one.",
0,
"2.6.0"},
{"ZUNIONSTORE",
"destination numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE (SUM|MIN|MAX)]",
"Add multiple sorted sets and store the resulting sorted set in a new key",
4,
"2.0.0"},
{"XADD",
"key [(MAXLEN|MINID) [(=|~)] threshold [LIMIT limit]] [NOMKSTREAM] (*|ID) field value",
"Appends a new entry to a stream",
14,
"5.0.0"},
{"SET",
"key value [(EX seconds|PX milliseconds|EXAT timestamp|PXAT milliseconds-timestamp|KEEPTTL)] [(NX|XX)] [GET]",
"Set the string value of a key",
1,
"1.0.0"},
};

#endif

