/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redis_jni_Redis */

#ifndef _Included_redis_jni_Redis
#define _Included_redis_jni_Redis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redis_jni_Redis
 * Method:    start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_redis_jni_Redis_start
  (JNIEnv *, jclass, jstring);

/*
 * Class:     redis_jni_Redis
 * Method:    eventloop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_redis_jni_Redis_eventloop
  (JNIEnv *, jclass);

/*
 * Class:     redis_jni_Redis
 * Method:    command
 * Signature: ([[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_redis_jni_Redis_command
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
