proc crm_read_config_file {} {
    set fd [open [srv 0 config_file] r]
    set content [read $fd]
    close $fd
    return $content
}

proc crm_config_file_mtime {} {
    return [file mtime [srv 0 config_file]]
}

proc crm_count_directive {name} {
    set n 0
    foreach line [split [crm_read_config_file] "\n"] {
        set trimmed [string trim $line]
        if {$trimmed eq "" || [string match "#*" $trimmed]} continue
        if {[lindex [split $trimmed] 0] eq $name} {incr n}
    }
    return $n
}

start_server {tags {"config-rewrite-mode external:skip"}} {
    test {config-rewrite-mode default is any-modified} {
        assert_equal {any-modified} [lindex [r config get config-rewrite-mode] 1]
    }

    test {config-rewrite-mode is immutable at runtime} {
        assert_error "*immutable*" {r config set config-rewrite-mode runtime-modified}
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified}} {
    test {runtime-modified - no runtime changes leaves file untouched} {
        set before [crm_read_config_file]
        set mtime_before [crm_config_file_mtime]
        after 1100
        r config rewrite
        assert_equal $before [crm_read_config_file]
        assert_equal $mtime_before [crm_config_file_mtime]
    }

    test {runtime-modified - CONFIG SET multiple configs emits all of them} {
        r config set timeout 30 maxmemory 50mb
        r config rewrite
        set content [crm_read_config_file]
        assert_match "*timeout 30*" $content
        assert_match "*maxmemory 50mb*" $content
    }

    test {runtime-modified - second consecutive REWRITE with no changes is a no-op} {
        # First REWRITE persists the timeout/maxmemory changes from the prior
        # test; file mtime bumps. The dict gets cleared on success.
        after 1100
        set mtime_before [crm_config_file_mtime]
        r config rewrite
        assert_equal $mtime_before [crm_config_file_mtime]
    }

    test {runtime-modified - SET non-default then SET default overwrites stale line} {
        r config set timeout 30
        r config rewrite
        assert_match "*timeout 30*" [crm_read_config_file]

        r config set timeout 0
        r config rewrite
        set content [crm_read_config_file]
        assert_match "*timeout 0*" $content
        assert_equal 0 [regexp {(^|\n)timeout 30(\s|$)} $content]

        restart_server 0 true false
        assert_equal {timeout 0} [r config get timeout]
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified maxmemory 100mb timeout 45}} {
    test {runtime-modified - existing non-default lines preserved when untouched} {
        r config rewrite
        set content [crm_read_config_file]
        assert_match "*maxmemory 100mb*" $content
        assert_match "*timeout 45*" $content
        assert_equal 0 [regexp {Generated by CONFIG REWRITE} $content]
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified}} {
    test {runtime-modified - no ACL changes does not emit user lines} {
        r config rewrite
        assert_equal 0 [crm_count_directive user]
    }

    test {runtime-modified - ACL SETUSER emits the full user list} {
        r acl setuser alice on nopass +@all
        r config rewrite
        set content [crm_read_config_file]
        assert {[crm_count_directive user] >= 2}
        assert_match "*user alice*" $content
        assert_match "*user default*" $content
    }

    test {runtime-modified - ACL DELUSER emits the full user list with the removed user gone} {
        r acl deluser alice
        r config rewrite
        set content [crm_read_config_file]
        assert_match "*user default*" $content
        assert_equal 0 [regexp {(^|\n)user alice\s} $content]
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified}} {
    test {runtime-modified - CONFIG SET via alias name marks the primary config} {
        # slave-priority is an alias for replica-priority (default 100).
        # Setting via the alias must still cause the primary to be emitted.
        r config set slave-priority 50
        r config rewrite
        set content [crm_read_config_file]
        # The primary name should land in the file (the alias entry is
        # skipped by ALIAS_CONFIG in the rewrite loop).
        assert_match "*replica-priority 50*" $content
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified}} {
    test {runtime-modified - REPLICAOF emits the replicaof line} {
        # No real master at this address — REPLICAOF just sets the config.
        r replicaof 127.0.0.1 1
        r config rewrite
        assert_match "*replicaof 127.0.0.1 1*" [crm_read_config_file]
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified replicaof "127.0.0.1 1"}} {
    test {runtime-modified - REPLICAOF NO ONE clears the stale replicaof line} {
        # Sanity: the file as loaded must contain the startup replicaof line.
        assert_match "*replicaof 127.0.0.1 1*" [crm_read_config_file]

        r replicaof no one
        r config rewrite
        set content [crm_read_config_file]
        assert_equal 0 [regexp {(^|\n)replicaof\s} $content]
    }
}

start_server [list \
        overrides {config-rewrite-mode runtime-modified} \
        config_lines [list user "default on nopass ~* &* +@all"] \
        tags {"config-rewrite-mode external:skip"}] {
    test {runtime-modified - CONFIG SET requirepass keeps user default consistent in file} {
        r config set requirepass newpass
        r config rewrite
        set content [crm_read_config_file]
        assert_match "*requirepass*newpass*" $content
        # The stale `user default on nopass` line must not survive: either
        # the rewrite re-emits user default with the new password, or drops
        # the original line. Either is fine; a passive `nopass` line is not.
        assert_equal 0 [regexp {(^|\n)user default on nopass} $content]
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified}} {
    test {runtime-modified - DELUSER of non-existent user does not set acl_modified} {
        set deleted [r acl deluser ghost-user]
        assert_equal 0 $deleted
        r config rewrite
        assert_equal 0 [crm_count_directive user]
    }
}

set crm_aclfile_dir [tmpdir "crm-aclfile"]
set crm_aclfile_path [file join $crm_aclfile_dir "users.acl"]
set fd [open $crm_aclfile_path w]
puts $fd "user default on nopass ~* &* +@all"
close $fd

start_server [list overrides [list "config-rewrite-mode" "runtime-modified" "dir" $crm_aclfile_dir "aclfile" "users.acl"] tags {"config-rewrite-mode external:skip"}] {
    test {runtime-modified - aclfile mode skips user lines regardless of acl_modified} {
        r acl setuser bob on nopass +@all
        r config rewrite
        assert_equal 0 [crm_count_directive user]
    }
}

start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified enable-debug-command yes}} {
    test {runtime-modified - DEBUG config-rewrite-force-all emits the full snapshot} {
        set before_lines [llength [split [crm_read_config_file] "\n"]]
        r debug config-rewrite-force-all
        set after_lines [llength [split [crm_read_config_file] "\n"]]
        assert {$after_lines > $before_lines + 50}
        set content [crm_read_config_file]
        assert_match "*daemonize*" $content
        assert_match "*latency-tracking-info-percentiles*" $content
        assert_match "*user default*" $content
    }
}

start_server [list overrides {config-rewrite-mode runtime-modified} \
                   omit {save} \
                   config_lines [list save {3600 1} save {300 100}] \
                   tags {"config-rewrite-mode external:skip"}] {
    test {runtime-modified - multi-arg save replaces all original save lines} {
        r config set save "7200 1 1800 50"
        r config rewrite
        # Two save points → two save lines, replacing the two original lines.
        assert_equal 2 [crm_count_directive save]
        set content [crm_read_config_file]
        assert_match "*save 7200 1*" $content
        assert_match "*save 1800 50*" $content
        # Original values must be gone.
        assert_equal 0 [regexp {(^|\n)save 3600 1\s*\n} $content]
        assert_equal 0 [regexp {(^|\n)save 300 100\s*\n} $content]
    }
}

# Spawn a standalone sentinel for the CONFIG REWRITE filtering tests, run
# the body, and tear it down. Same shape as start_server.
#
# These tests live in the unit suite (not tests/sentinel/) because they're
# about REWRITE behavior, not Sentinel's quorum / failover machinery. The
# shared 5-sentinel cluster used by the sentinel suite can't easily be
# reconfigured per-test, and spawning a 6th would skew the quorum count.
#
# We bypass start_server because its readiness check waits for
# "Server initialized" in the log, which Sentinel does not emit. Instead
# we exec redis-server --sentinel directly, poll until reachable, and tear
# down via the catch+rethrow pattern so cleanup runs even on test errors.
proc start_crm_sentinel {code} {
    set ::crm_sentinel_dir [file normalize [tmpdir "crm-sentinel"]]
    set ::crm_sentinel_conf [file join $::crm_sentinel_dir "sentinel.conf"]
    set ::crm_sentinel_log [file join $::crm_sentinel_dir "sentinel.log"]
    set ::crm_sentinel_port [find_available_port $::baseport $::portcount]
    set fd [open $::crm_sentinel_conf w]
    puts $fd "port $::crm_sentinel_port"
    puts $fd "dir $::crm_sentinel_dir"
    puts $fd "daemonize yes"
    puts $fd "logfile \"$::crm_sentinel_log\""
    puts $fd "config-rewrite-mode runtime-modified"
    close $fd

    exec src/redis-server $::crm_sentinel_conf --sentinel
    if {![server_is_up $::host $::crm_sentinel_port 100]} {
        fail "Sentinel did not come up on port $::crm_sentinel_port"
    }
    set ::crm_sentinel_client [redis $::host $::crm_sentinel_port 0 $::tls]

    set err [catch {uplevel 1 $code} result]
    catch {$::crm_sentinel_client shutdown nosave}
    $::crm_sentinel_client close
    if {$err} { error $result $::errorInfo }
}

proc crm_read_sentinel_conf {} {
    set fd [open $::crm_sentinel_conf r]
    set content [read $fd]
    close $fd
    return $content
}

proc crm_count_sentinel_directive {name} {
    set n 0
    foreach line [split [crm_read_sentinel_conf] "\n"] {
        set trimmed [string trim $line]
        if {$trimmed eq "" || [string match "#*" $trimmed]} continue
        if {[lindex [split $trimmed] 0] eq $name} {incr n}
    }
    return $n
}

start_crm_sentinel {
    test {runtime-modified + sentinel - sentinel state always emitted} {
        $::crm_sentinel_client sentinel monitor mymaster 127.0.0.1 6379 1
        set content [crm_read_sentinel_conf]
        assert_match "*sentinel myid*" $content
        assert_match "*sentinel monitor mymaster 127.0.0.1 6379 1*" $content
        assert_match "*sentinel current-epoch*" $content
    }

    test {runtime-modified + sentinel - general server configs not added by rewrite} {
        set port_count_before [crm_count_sentinel_directive port]
        set dir_count_before [crm_count_sentinel_directive dir]
        set user_count_before [crm_count_sentinel_directive user]
        set ltip_count_before [crm_count_sentinel_directive latency-tracking-info-percentiles]

        $::crm_sentinel_client sentinel set mymaster down-after-milliseconds 3500
        $::crm_sentinel_client sentinel remove mymaster
        $::crm_sentinel_client sentinel monitor mymaster 127.0.0.1 6379 1

        assert_equal $port_count_before [crm_count_sentinel_directive port]
        assert_equal $dir_count_before [crm_count_sentinel_directive dir]
        assert_equal $user_count_before [crm_count_sentinel_directive user]
        assert_equal $ltip_count_before [crm_count_sentinel_directive latency-tracking-info-percentiles]
    }
}

# FAILOVER mutates server.masterhost without going through replicaofCommand,
# so it must mark the replicaof config directly. Without that mark, the
# new replica's REWRITE in runtime-modified mode silently drops the
# replicaof line and a restart would silently come back as a primary.
start_server {tags {"config-rewrite-mode external:skip"} overrides {config-rewrite-mode runtime-modified save {}}} {
    start_server {overrides {save {}}} {
        set primary [srv -1 client]
        set primary_host [srv -1 host]
        set primary_port [srv -1 port]
        set replica [srv 0 client]
        set replica_host [srv 0 host]
        set replica_port [srv 0 port]

        test {runtime-modified - FAILOVER persists new replicaof on the old primary} {
            # Sanity: the primary is the one under config-rewrite-mode runtime-modified.
            assert_equal {any-modified} [lindex [$replica config get config-rewrite-mode] 1]
            assert_equal {runtime-modified} [lindex [$primary config get config-rewrite-mode] 1]

            $replica replicaof $primary_host $primary_port
            wait_for_sync $replica
            wait_for_condition 50 100 {
                [string match "*slave0:*,state=online*" [$primary info replication]]
            } else {
                fail "replica did not come online before failover"
            }

            assert_equal "OK" [$primary failover to $replica_host $replica_port]
            wait_for_condition 50 100 {
                [s -1 master_failover_state] == "no-failover"
            } else {
                fail "FAILOVER did not complete"
            }
            assert_match *slave* [$primary role]

            # The old primary is now a replica of the old replica. REWRITE
            # in runtime-modified mode must emit replicaof pointing at the
            # new master, otherwise restart would silently revert.
            $primary config rewrite
            set fd [open [srv -1 config_file] r]
            set content [read $fd]
            close $fd
            assert_match "*replicaof $replica_host $replica_port*" $content
        }
    }
}
