name: "Codecov"

# Enabling on each push is to display the coverage changes in every PR, 
# where each PR needs to be compared against the coverage of the head commit
on: [push, pull_request]

jobs:
  code-coverage:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

    - name: Install lcov and run test
      run: |
        sudo apt-get install lcov
        make lcov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238  # v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./src/redis.info
